# Generated by Django 4.1.7 on 2023-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('free_bikes', models.IntegerField(blank=True, null=True, verbose_name='Disponibles')),
                ('empty_slots', models.IntegerField(blank=True, null=True, verbose_name='Ranuras vacias')),
                ('timestamp', models.DateTimeField(verbose_name='Fecha')),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('extra', models.JSONField()),
            ],
        ),
    ]
