# Generated by Django 4.1.7 on 2023-02-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeSantiago', '0002_alter_station_latitude_alter_station_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='extra',
            field=models.JSONField(verbose_name='Dirección'),
        ),
    ]
