# Generated by Django 4.1.7 on 2023-02-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeSantiago', '0003_alter_station_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slots', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('payment', models.JSONField(blank=True, null=True, verbose_name='Método de pagos')),
                ('has_ebikes', models.BooleanField(verbose_name='¿Tiene ebikes?')),
                ('payment_terminal', models.BooleanField(verbose_name='Terminal de pagos')),
                ('last_updated', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ultima actualización')),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BikeSantiago.adress'),
        ),
    ]
