# Generated by Django 4.1.7 on 2023-02-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeSantiago', '0004_adress_alter_station_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Método de pagos'),
        ),
    ]
