# Generated by Django 4.1.7 on 2023-02-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeSantiago', '0005_alter_adress_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
